import {
  Award,
  BookOpen,
  Briefcase,
  Building2,
  Cloud,
  Code2,
  Cpu,
  Eye,
  Gavel,
  Globe,
  Handshake,
  Headphones,
  Layers,
  Lightbulb,
  LineChart,
  Lock,
  Network,
  Rocket,
  Settings,
  Shield,
  ShieldCheck,
  Sparkles,
  Star,
  Target,
  Terminal,
  TrendingUp,
  Trophy,
  Users,
  Zap,
  type LucideIcon,
} from "lucide-react";

/** Icons available in about page admin pickers (values + advantage cards). */
export const ABOUT_PAGE_ICON_OPTIONS = [
  "lightbulb",
  "shieldCheck",
  "handshake",
  "trophy",
  "cloud",
  "network",
  "gavel",
  "trendingUp",
  "headset",
  "rocket",
  "target",
  "eye",
  "zap",
  "globe",
  "users",
  "building2",
  "briefcase",
  "cpu",
  "lock",
  "award",
  "star",
  "sparkles",
  "bookOpen",
  "layers",
  "settings",
  "lineChart",
  "shield",
  "code2",
  "terminal",
] as const;

const ABOUT_PAGE_ICONS: Record<string, LucideIcon> = {
  lightbulb: Lightbulb,
  Lightbulb: Lightbulb,
  innovation: Lightbulb,
  shieldCheck: ShieldCheck,
  ShieldCheck: ShieldCheck,
  shield: Shield,
  Shield: Shield,
  security: ShieldCheck,
  handshake: Handshake,
  Handshake: Handshake,
  trophy: Trophy,
  Trophy: Trophy,
  award: Award,
  Award: Award,
  cloud: Cloud,
  Cloud: Cloud,
  online: Cloud,
  network: Network,
  Network: Network,
  nodes: Network,
  corporate: Network,
  gavel: Gavel,
  Gavel: Gavel,
  compliance: Gavel,
  trendingUp: TrendingUp,
  TrendingUp: TrendingUp,
  chart: LineChart,
  lineChart: LineChart,
  LineChart: LineChart,
  headset: Headphones,
  headphones: Headphones,
  rocket: Rocket,
  Rocket: Rocket,
  target: Target,
  Target: Target,
  eye: Eye,
  Eye: Eye,
  zap: Zap,
  Zap: Zap,
  globe: Globe,
  Globe: Globe,
  users: Users,
  Users: Users,
  building2: Building2,
  Building2: Building2,
  briefcase: Briefcase,
  Briefcase: Briefcase,
  cpu: Cpu,
  Cpu: Cpu,
  lock: Lock,
  Lock: Lock,
  star: Star,
  Star: Star,
  sparkles: Sparkles,
  Sparkles: Sparkles,
  bookOpen: BookOpen,
  BookOpen: BookOpen,
  layers: Layers,
  Layers: Layers,
  settings: Settings,
  Settings: Settings,
  code2: Code2,
  Code2: Code2,
  innovationCode: Code2,
  terminal: Terminal,
  Terminal: Terminal,
};

export function resolveAboutPageIcon(name: string | undefined, fallback: LucideIcon): LucideIcon {
  return ABOUT_PAGE_ICONS[name ?? ""] ?? fallback;
}
